# Generated by Django 4.2.5 on 2023-09-05 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('action', models.TextField(verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.CharField(default=datetime.timedelta(days=1), max_length=30, verbose_name='периодичность')),
                ('reward', models.CharField(max_length=150, verbose_name='вознаграждение')),
                ('duration', models.CharField(default=datetime.timedelta(seconds=600), max_length=30, verbose_name='время на выполнение')),
                ('is_publish', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('pleasant_habit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
