# Generated by Django 4.2.5 on 2023-09-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_user_habit_owner_alter_habit_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='периодичность'),
        ),
    ]
