# Generated by Django 4.2.5 on 2023-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_duration_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, default='00:00', null=True, verbose_name='время'),
        ),
    ]
